-- ============================================================
-- Spot Radar schema: สมาชิก (allowlist) + จุดบนแผนที่ + สิทธิ์ (RLS)
-- ============================================================

-- 1) รายชื่ออีเมลที่อนุญาต ------------------------------------------------
create table if not exists public.members (
  email     text primary key check (email = lower(email) and position('@' in email) > 1),
  is_admin  boolean not null default false,
  added_at  timestamptz not null default now()
);

-- 2) จุดบนแผนที่ ------------------------------------------------------------
create table if not exists public.points (
  id               bigint generated by default as identity primary key,
  code             text,
  list             text not null default 'user' check (list in ('od', 'num', 'user')),
  name             text not null check (char_length(name) between 1 and 200),
  note             text check (note is null or char_length(note) <= 300),
  description      text check (description is null or char_length(description) <= 1000),
  category         text not null default 'other',
  lat              double precision check (lat is null or lat between -90 and 90),
  lng              double precision check (lng is null or lng between -180 and 180),
  precision_level  text not null default 'exact' check (precision_level in ('exact', 'approx', 'none')),
  pos_source       text not null default 'member' check (pos_source in ('seed', 'member')),
  active           boolean not null default true,
  gmaps_query      text,
  created_by       uuid references auth.users (id) on delete set null,
  created_by_email text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz,
  updated_by_email text
);

-- 3) ฟังก์ชันตรวจสิทธิ์ -------------------------------------------------------
create or replace function public.is_member() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.members m
    where m.email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.members m
    where m.email = lower(coalesce(auth.jwt() ->> 'email', '')) and m.is_admin
  );
$$;

revoke all on function public.is_member() from public, anon;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_member() to authenticated;
grant execute on function public.is_admin() to authenticated;

-- 4) กันการปลอมผู้สร้าง และบันทึกผู้แก้ไข -------------------------------------
create or replace function public.points_before_write() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      new.created_by := auth.uid();
      new.created_by_email := lower(auth.jwt() ->> 'email');
      new.list := 'user';
      new.code := null;
      new.pos_source := 'member';
    end if;
    if new.code is null or new.code = '' then
      new.code := 'U' || new.id;
    end if;
  else
    new.id := old.id;
    new.created_by := old.created_by;
    new.created_by_email := old.created_by_email;
    new.created_at := old.created_at;
    if auth.uid() is not null then
      new.list := old.list;
      new.code := old.code;
      new.updated_by_email := lower(auth.jwt() ->> 'email');
    end if;
    new.updated_at := now();
  end if;
  if new.lat is null or new.lng is null then
    new.lat := null; new.lng := null; new.precision_level := 'none';
  elsif new.precision_level = 'none' then
    new.precision_level := 'exact';
  end if;
  return new;
end $$;

drop trigger if exists points_before_write on public.points;
create trigger points_before_write
  before insert or update on public.points
  for each row execute function public.points_before_write();

-- 5) สิทธิ์ระดับแถว (RLS) -----------------------------------------------------
alter table public.members enable row level security;
alter table public.points  enable row level security;

revoke all on public.members, public.points from anon;
grant select, insert, update, delete on public.members, public.points to authenticated;

drop policy if exists members_select on public.members;
drop policy if exists members_insert on public.members;
drop policy if exists members_update on public.members;
drop policy if exists members_delete on public.members;
create policy members_select on public.members for select to authenticated
  using (email = lower(coalesce(auth.jwt() ->> 'email', '')) or public.is_admin());
create policy members_insert on public.members for insert to authenticated
  with check (public.is_admin());
create policy members_update on public.members for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy members_delete on public.members for delete to authenticated
  using (public.is_admin());

drop policy if exists points_select on public.points;
drop policy if exists points_insert on public.points;
drop policy if exists points_update on public.points;
drop policy if exists points_delete on public.points;
create policy points_select on public.points for select to authenticated
  using (public.is_member());
create policy points_insert on public.points for insert to authenticated
  with check (public.is_member());
create policy points_update on public.points for update to authenticated
  using (public.is_member()) with check (public.is_member());
create policy points_delete on public.points for delete to authenticated
  using (public.is_member() and (public.is_admin() or created_by = auth.uid()));

-- 6) สมัครได้เฉพาะอีเมลที่อยู่ในรายชื่อ ---------------------------------------
create or replace function public.enforce_member_signup() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.email is null
     or not exists (select 1 from public.members m where m.email = lower(new.email)) then
    raise exception 'EMAIL_NOT_ALLOWED';
  end if;
  return new;
end $$;

drop trigger if exists enforce_member_signup on auth.users;
create trigger enforce_member_signup
  before insert or update of email on auth.users
  for each row execute function public.enforce_member_signup();

-- 7) อัปเดตสดเมื่อมีคนเพิ่ม/แก้จุด (Realtime) ---------------------------------
do $$ begin
  alter publication supabase_realtime add table public.points;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
